# Generated by Django 4.1 on 2022-09-12 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='size',
            new_name='key',
        ),
    ]
