# Generated by Django 4.1 on 2022-09-12 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0002_rename_size_pizza_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='key',
            new_name='size',
        ),
    ]
