# Generated by Django 4.1.1 on 2022-09-12 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0004_alter_pizza_size_alter_size_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='size',
            field=models.ForeignKey(default=1, help_text='Selec the size of the pizza.', on_delete=django.db.models.deletion.CASCADE, to='pizzaapp.size'),
        ),
    ]
