# Generated by Django 4.1.1 on 2022-09-12 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0010_alter_pizza_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
