# Generated by Django 4.1.1 on 2022-09-13 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0017_alter_pizza_toppings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='toppings',
            field=models.CharField(choices=[('pepperoni', 'Pepperoni'), ('sausage', 'Sausage'), ('bacon', 'Bacon'), ('mushrooms', 'Mushrooms'), ('onions', 'Onions'), ('pineapple', 'Pineapple'), ('ham', 'Ham'), ('anchovies', 'Anchovies'), ('extra cheese', 'Extra Cheese')], default=b']', max_length=100),
        ),
    ]
