# Generated by Django 4.1.1 on 2022-09-14 14:57

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0018_alter_pizza_toppings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='toppings',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('pepperoni', 'Pepperoni'), ('sausage', 'Sausage'), ('bacon', 'Bacon'), ('mushrooms', 'Mushrooms'), ('onions', 'Onions'), ('pineapple', 'Pineapple'), ('ham', 'Ham'), ('anchovies', 'Anchovies'), ('extra cheese', 'Extra Cheese')], default=b']', max_length=100),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='pizzaapp.pizza')),
            ],
        ),
    ]
