# Generated by Django 4.1.1 on 2022-09-14 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0020_remove_cart_cart_cart_size_cart_toppings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='title',
            field=models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], max_length=20),
        ),
    ]
