# Generated by Django 4.1.1 on 2022-09-15 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0021_alter_size_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
