# Generated by Django 4.1.1 on 2022-09-15 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0024_remove_cart_cart_cart_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart',
            field=models.JSONField(default=list),
        ),
    ]
