# Generated by Django 4.1.1 on 2022-09-15 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0026_remove_cart_cart_cart_size_cart_toppings'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='is_ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
