# Generated by Django 4.1.1 on 2023-01-19 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0027_pizza_is_ordered_delete_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='size',
            field=models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], max_length=10),
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
