# Generated by Django 4.1.1 on 2023-01-20 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0030_remove_pizza_toppings_pizza_topping1_pizza_topping2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='topping1',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='topping2',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='topping3',
        ),
        migrations.AddField(
            model_name='pizza',
            name='toppings',
            field=models.CharField(default=b']', max_length=100),
        ),
    ]
