# Generated by Django 4.1.1 on 2023-01-20 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0033_remove_pizza_toppings_pizza_topping1_pizza_topping2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='topping2',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='topping3',
        ),
        migrations.AlterField(
            model_name='pizza',
            name='topping1',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Pepperoni'),
        ),
    ]
