# Generated by Django 4.1.1 on 2023-01-20 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0034_remove_pizza_topping2_remove_pizza_topping3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='topping1',
        ),
    ]
