# Generated by Django 4.1.1 on 2023-01-20 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0035_remove_pizza_topping1'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='topping1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pizza',
            name='topping2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pizza',
            name='topping3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
