# Generated by Django 4.1.1 on 2023-01-20 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0036_pizza_topping1_pizza_topping2_pizza_topping3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='topping1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='topping2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='topping3',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
