# Generated by Django 4.1.1 on 2023-01-21 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0037_alter_pizza_topping1_alter_pizza_topping2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='topping1',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='topping2',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='topping3',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
